//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilProcess_BahisKupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCouponMasters
    {
        public System.Guid CouponId { get; set; }
        public string IntegrationId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Multiply { get; set; }
        public string Combinations { get; set; }
        public Nullable<int> GameColumns { get; set; }
        public Nullable<decimal> MaxOdd { get; set; }
        public Nullable<decimal> MaxPrize { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> Prize { get; set; }
        public Nullable<decimal> Odd { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<byte> CouponType { get; set; }
        public string AccountTerm { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<bool> FindSuccess { get; set; }
        public Nullable<int> PredefinedCouponId { get; set; }
        public byte Status { get; set; }
    }
}
