//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilProcess_BahisKupon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int MemberId { get; set; }
        public string MemberCode { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string Id { get; set; }
        public string Address { get; set; }
        public string HomePhone { get; set; }
        public string BusinessPhone { get; set; }
        public string MobilePhone { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string EMail { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public int PlatformId { get; set; }
        public int SourceId { get; set; }
        public int LanguageId { get; set; }
        public byte IdStatus { get; set; }
        public byte Status { get; set; }
        public string IP { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Agent { get; set; }
        public Nullable<int> Zip { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> SupportedTeam { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<bool> IsEmailActivated { get; set; }
        public string GoogleAnalyticsMS1 { get; set; }
        public string GoogleAnalyticsMS2 { get; set; }
    }
}
